### ISSUE TITLE
SCC: Cannot specify partial seLinuxOptions

### ISSUE THREAD

**Issue by Raniz85** [openshift/apiserver-library-go#103]
I'm running GitLab Runner on OpenShift and GitLab runner only allows me to specify _type_ of _seLinuxOptions_, the rest of the values are unspecified.

This requires me to use an SCC with _RunAsAny_ for  _seLinuxContext_ since the logic for validating it matches on all fields.

If I don't specify a field in the SCC it seems to validate against a default value, however the value from the pod is not replaced by a default if missing/empty which means my pod is rejected.

Example SCC:

```yaml
kind: SecurityContextConstraints
apiVersion: security.openshift.io/v1
metadata:
  name: gitlab-runner-jobs
allowHostDirVolumePlugin: false
allowHostIPC: false
allowHostNetwork: false
allowHostPID: false
allowHostPorts: false
allowPrivilegeEscalation: true
allowPrivilegedContainer: false
runAsUser:
  type: RunAsAny
seLinuxContext:
  type: MustRunAs
  seLinuxOptions:
    type: spc_t
fsGroup:
  type: RunAsAny
supplementalGroups:
  type: RunAsAny
allowedCapabilities:
  - SYS_CHROOT
  - SETUID
  - SETGID
  - SETFCAP
volumes:
  - configMap
  - downwardAPI
  - emptyDir
  - persistentVolumeClaim
  - projected
  - secret
readOnlyRootFilesystem: false
users:
  - "system:serviceaccount:gitlab-runner-jobs:gitlab-runner-jobs"

```
This rejects a pod with

```yaml
    securityContext:
      seLinuxOptions:
        type: spc_t
```
